### ISSUE TITLE
Extract original osm type and id

### ISSUE THREAD

**Issue by dianashk** [pelias/fences-cli#11]
Currently osmium doesn't return an id or original type info. Need to fork the node wrapper and add that data to the area object.

**Comment by andrisi** [comment]
Will you release the next round of monthly files using this fix? And if so, when? Thanks!

**Comment by dianashk** [comment]
@andrisi, this will be in the next build. I'm wrapping up the addition of version/timestamp/license info to each output file. Should be another day at most. Then we'll kick off a fresh build. Cheers.

**Comment by andrisi** [comment]
@dianashk Thanks! This helps with my own project, and contributing back to OSM too.
